version: '3'

services:
  a:
    build: ./A
    ports:
      - 8888:80
    env_file:
      - ./.env
    depends_on:
      - rabbitmqserver
    restart: always
  b:
    build: ./B
    env_file:
      - ./.env
    depends_on:
      - rabbitmqserver
    restart: always
  c:
    build: ./C
    env_file:
      - ./.env
    restart: always
    depends_on:
      - rabbitmqserver
      - b
  rabbitmqserver:
    image: rabbitmq:3-management
    volumes:
      - rabbitmqetc:/etc/rabbitmq/
      - rabbitmqdata:/var/lib/rabbitmq/mnesia/
      - rabbitmqlogs:/var/log/rabbitmq/
    env_file:
      - ./.env
    ports:
      - 15672:15672
      - 5672:5672
  mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    env_file:
      - ./.env
    volumes:
      - mongodata:/data/db

volumes:
  rabbitmqetc:
  rabbitmqdata:
  rabbitmqlogs:
  mongodata: